name: user-service
replicaCount: 1
deployment:
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
image:
  repository: jakubpavlicek/user-service
  tag: 0.0.1
service:
  ports:
    http: 8020
    grpc: 9020
database:
  enabled: true
probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10