tempo:
  reportingEnabled: false

  receivers:
    jaeger: { }

  ingester:
    trace_idle_period: 5s
    flush_check_period: 10s
    max_block_duration: 10m
    complete_block_timeout: 15m
    lifecycler:
      ring:
        replication_factor: 1

  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - local-blocks
          - span-metrics

  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus:9090/api/v1/write
    processor:
      local_blocks:
        filter_server_spans: false
      span_metrics:
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
          - service_name
          - operation
          - status_code
      service_graphs:
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
          - service_name
          - operation
          - status_code

persistence:
  enabled: true
  storageClassName: standard