database:
  credentials:
    username: ENC[AES256_GCM,data:3ufdtUPtzg==,iv:lbyjm9Bv1yKMAWm6sUF+1Tiu+j9m/WwZ5zrvyUwVIQs=,tag:qGZ/v4be47MTqAqP4W02xw==,type:str]
    password: ENC[AES256_GCM,data:8O7xsw==,iv:07870AFLqRc245k4f1Hj1viUYLqruCjk3wOCxufe2RE=,tag:VA/2huK86TFBx9rfCpYdLw==,type:str]
    proxy:
      username: ENC[AES256_GCM,data:NL6MQBEtmwjozFo=,iv:yVH0ejC+xP+zXBSSd3gR3otfYBKdgMxWBWlQaGszub8=,tag:J3VXLNbxAAce9RdIZ2YcHA==,type:str]
      password: ENC[AES256_GCM,data:hVK2CQ==,iv:DGvbqXYjsXkRCW8aBsS04JrOviG2QWI9q4ZJJD+Jyw4=,tag:u88QzPxQ1HxQP2zkAwdd3g==,type:str]
      targetUsername: ENC[AES256_GCM,data:7r17J3nI2Q0=,iv:M6W79dd8vJSKUN+MAhvI+R/tUvtFf7xhwiZJV3KcbYw=,tag:8bCzLWs1kZLdco9UnMDXPg==,type:str]
sops:
  age:
    - recipient: age1g0tt02e6duuerd5wkakkcw03ng5yunhnh6ms0mj3908fwn0qx9lqlwzdx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN3I5QnhodWpkRFFrd3Fv
        Lytnd1lzNDgyK3VHeTBaRTkzQ3FKU2V0SXk4CnRUNFRIZnQ3VmNFSGFzYkg0SlZ0
        L2czenpvS0UvTng0dHlMRXZhc1QwZWcKLS0tIG9mMndIazcrTjhNaDFoRmc4T0Yw
        ZGN3SVBEYzlzb1lGSlZCbHVXbW40akEK7IcQCCLOYARxu2u5CkncRT2UvIhAgby1
        1qfK2SyCKTfSy6GWGUQAVPGtF3QrulO/vUhPrRTBWza2+ptblUZj5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T10:27:50Z"
  mac: ENC[AES256_GCM,data:1aBrLgNuXJGEvi0JDfr+naKQeQUw4+fuSeRhzPYhR6yeNzEh5Me2jTTc862JDgwzDxKaioj4J1wf0i401ie1a4NfofoLeqGeNv7HlX77Wm5dAg0/6amYdgVhulNIAGXyvSpDiXyOzgeozXEiju7tAEMUqqS01N7OTfu70zkTXTA=,iv:fvk+IZWOKLYK1poMp94Nb1RCwuLR0PvKD4tVi4X6ZXs=,tag:Zu1/HQkZt3uXwCcV/Jntmw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0