secrets:
  grafana-secret:
    username: ENC[AES256_GCM,data:gjccUzw=,iv:Miftixrk3yD/OcoYyBqukOLKaeN7FCJehtNljJ7ouZ8=,tag:bnGp9NYIkxZRDQVUWyx2PQ==,type:str]
    password: ENC[AES256_GCM,data:G6/lZ9U=,iv:Y+MXQYyiwbxE0B+UVXvB8RGH0GPCH/8KoCaw2meN9AE=,tag:+J5UKSeR67TztOJHMDA/Jw==,type:str]
  keycloak-postgresql-secret:
    postgresql-admin-password: ENC[AES256_GCM,data:tG2WwjRKzVA=,iv:oBV5/2mhHD8Rcvo25uGqdUae9u20kEhgKXX8wubzAnk=,tag:BWK0E7ieM4C+Qs30KeWsBw==,type:str]
    postgresql-user-password: ENC[AES256_GCM,data:PewEde30uKA=,iv:yWJ4F0h5berS/20/22TiJ2xqpzBvD/QFYjYNa6kGpw0=,tag:/bhdyWiVpkgVBlyOVgemUg==,type:str]
  redis-cache-secret:
    redis-password: ENC[AES256_GCM,data:wN4Jbi0=,iv:9+GBMZT3WOr4r3z9lnaMfRFzGAIBzpmCWt18ECIi0vI=,tag:Mbc7hY1xG2YduZQKYV7ppw==,type:str]
  redis-rate-limiter-secret:
    redis-password: ENC[AES256_GCM,data:9XjJ9WU=,iv:vNUZx4OOZeZi8jPWkDLCLsOIjSLe5xYSStho8X2ljzA=,tag:buQzHMctsIYZ5VtsViP5Pw==,type:str]
sops:
  age:
    - recipient: age1g0tt02e6duuerd5wkakkcw03ng5yunhnh6ms0mj3908fwn0qx9lqlwzdx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRHlzNDU4MVJlbnBNSitu
        QVR0VGFEbnpZeWphYlhSUGljYThZWkpYMkRvCkJsN3V1QTEwbDlDS0NsQmhBd3hm
        Q0NpUnBMMXNGMWVzRjA1ZXVpQXJYTG8KLS0tIHRpaUFUWUJJSWRkN2xhYW1NbmpT
        dDVNczdlNXdXcXpzZG1MY3FSTzg0UnMKo9CWyzh1v70tmkuMoKAJrkGYi10fFMgb
        W1jBh+2n4ZikhLsjj5n6sTKfx77VcfrbStnyVauwQdk5AdUcRkwliQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T20:08:50Z"
  mac: ENC[AES256_GCM,data:8qQEPksYgN0URbmsy2fay9xhiupXqXDSYfzGBOgsDt+as9lqViT8RSjRmkxsD5/PSjfMo5g9AmjVHVKRjuNh7cXH7w8kzN+noJU+fEFcq5L6eWJAf03L9p5chmcOYO7//aypUvWXxzHviWAG40oHBNUx5B9iP9MUKtGEmPMUvg0=,iv:JqXtxsZEhmssTBtKgeP9oMXLC0A7caVqg5UN0/0lU9w=,tag:lM+0mhi+Oroq9VBvSiN7ag==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0