secrets:
  grafana-secret:
    username: ENC[AES256_GCM,data:0l35jcI=,iv:hdkY5dZvblEqSD8/VOzJynSLEDeQ2rvn1DJx+TFbAig=,tag:yHQ8HXuH0/WlbNwiQG6fCQ==,type:str]
    password: ENC[AES256_GCM,data:zycukJY=,iv:MTkNKRAv346WmJDU+ZHPb8Grar7yrB6FAdjpzvE5GPc=,tag:DGoDPOiZKe4QdrpfjLvHyg==,type:str]
  keycloak-postgresql-secret:
    postgresql-admin-password: ENC[AES256_GCM,data:xFmilqHgDkE=,iv:ngjHJj+jjBuSUc+QzNhL6ZAtzOQyLEG6NesKfiCTuJo=,tag:Vtlgo53Bc9SRpTd/Z2bmdQ==,type:str]
    postgresql-user-password: ENC[AES256_GCM,data:HJhYEBTTrQg=,iv:pgXK97s5NnqhnFFa7voprSTkd5/UIwoKGeMnopKZr4w=,tag:CBeg1kTmlWAbGOunlOjofQ==,type:str]
  redis-cache-secret:
    redis-password: ENC[AES256_GCM,data:iFc+TTE=,iv:5vXH9QXgYz5R/dEKwFYUvt426FrzXKQjm8InTM3wg5M=,tag:a+etbejsq2iefiY/c5BphA==,type:str]
  redis-rate-limiter-secret:
    redis-password: ENC[AES256_GCM,data:vQ6nS1U=,iv:hPwEPE7Ka2dt8YUryVtfV2wziSfqm8z/QtIlO9aASto=,tag:LqkHxrGk3Z4Ry0sNsvl1EA==,type:str]
sops:
  age:
    - recipient: age1g0tt02e6duuerd5wkakkcw03ng5yunhnh6ms0mj3908fwn0qx9lqlwzdx0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN1FhbDNpdTBTZ2RUWnNp
        aktENkNLQlpIUXc4YWJIYW9NZ1JFeHU0NjJBCjByanhMcUVIbjBDUmlZZThGKzRN
        WHB3a1I1S20wWVZQdzMycjZDUkRmVlUKLS0tIGhNOGhQMUhEaG51cFo3UzhZMGxr
        WCtnSWRBZitveDFXMWRMaTlUVVE4TEUKC9vPZ+3Hf2XlLuSaA1c+1XNcZ1ifqIR7
        OyiIbpFm0zzlnm7b+d9HzBFZT/bAh+COIgpwKv6jQbZOz/aCO1pykw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T10:27:33Z"
  mac: ENC[AES256_GCM,data:2LphUBg5hDnUOmpjl8vxoIZY2u+D72Sk7Pye0g9vEZrdQhHtRQj7R6/01KhD8RNHs6WwkBX3mA6n+KZxei1UJ/1JLob1wdYeSUcxG95+obkSekdy4ZW0Cwf84D2EzIFDIKPJrhd2wIoB+Ptc5Wv7uqlTAsYc84skIl/tnFzDfqI=,iv:0364UJzuWYjLGgA8JvQnBRLlRXv5BLwT+xfN/r6BI84=,tag:g1lgizEFFhNT3EvbtHj7NQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0