apiVersion: v2
name: metallb-config
description: Configuration chart for MetalLB
type: application
version: 0.0.2
appVersion: "0.0.1"
keywords:
  - metallb
  - ip-address-pool
  - l2-advertisement
home: https://github.com/JakubPavlicek/is-stag
sources:
  - https://github.com/JakubPavlicek/is-stag
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz