apiVersion: v2
name: cert-manager-config
description: Configuration chart for certificates managed by cert-manager
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz
