# Certificate configuration
certificates:
  # Name of the certificate issuer to use
  issuerName: selfsigned-issuer
  # Kind of issuer (Issuer or ClusterIssuer)
  issuerKind: Issuer
  
  # List of certificates to create
  certs:
    # Main application certificate
    - name: app-cert
      # Secret name where the certificate will be stored
      secretName: app-tls-cert
      # DNS names covered by this certificate
      dnsNames:
        - example.com
        - www.example.com