name: api-gateway
replicaCount: 1
deployment:
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
image:
  repository: jakubpavlicek/api-gateway
  tag: 0.0.1
service:
  ports:
    http: 8100
    grpc: null
database:
  enabled: false
probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 50
    periodSeconds: 20
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 50
    periodSeconds: 20