apiVersion: v2
name: client
description: A Helm chart for deploying an IS/STAG frontend client
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz