apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  gatewayClassName: nginx
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: grafana.is-stag.internal
      tls:
        mode: Terminate
        certificateRefs:
          - name: selfsigned-grafana-cert-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
