apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-route
spec:
  parentRefs:
    - name: public-gateway
      sectionName: https
      kind: Gateway
  hostnames:
    - is-stag.cz
  rules:
    # Keycloak
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: keycloak-http
          port: 8080

    # API Gateway
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api-gateway
          port: 8100

    # React Client
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: react-client
          port: 5173
