apiVersion: v2
name: client
description: A Helm chart for deploying an IS/STAG frontend client
type: application
version: 0.0.2
appVersion: "0.0.1"
keywords:
  - is-stag
  - frontend
  - client
  - typescript
  - react
home: https://github.com/JakubPavlicek/is-stag
sources:
  - https://github.com/JakubPavlicek/is-stag
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz