{{- if .Values.database.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-database-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.credentials.username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.credentials.password | b64enc | quote }}
  DATASOURCE_PROXY_USERNAME: {{ .Values.database.credentials.proxy.username | b64enc | quote }}
  DATASOURCE_PROXY_PASSWORD: {{ .Values.database.credentials.proxy.password | b64enc | quote }}
  DATASOURCE_TARGET_USERNAME: {{ .Values.database.credentials.proxy.targetUsername | b64enc | quote }}
{{- end }}
