apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-database-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
