apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  VITE_KEYCLOAK_URL: {{ .Values.keycloak.url | quote }}
  VITE_KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}
  VITE_API_URL: {{ .Values.api.url | quote }}
