apiVersion: v2
name: otel-config
description: Configuration chart for OpenTelemetry Collector and Instrumentation
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz