apiVersion: v2
name: gateway-config
description: Configuration chart for Gateway API resources
type: application
version: 0.0.2
appVersion: "0.0.1"
keywords:
  - gateway
  - gateway-api
  - routing
home: https://github.com/JakubPavlicek/is-stag
sources:
  - https://github.com/JakubPavlicek/is-stag
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz