apiVersion: v2
name: secrets
description: Configuration chart for secrets
type: application
version: 0.0.2
appVersion: "0.0.1"
keywords:
  - secrets
  - opaque
home: https://github.com/JakubPavlicek/is-stag
sources:
  - https://github.com/JakubPavlicek/is-stag
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz