apiVersion: v2
name: backend-service
description: A generic Helm chart for deploying an IS/STAG backend service
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz