name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  build-and-publish-client:
    runs-on: macos-26
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 25.1.0
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Setup Buildpacks Tools
        uses: buildpacks/github-actions/setup-tools@v5.9.5

      - name: Setup Buildpacks Pack
        uses: buildpacks/github-actions/setup-pack@v5.9.5

      - name: Setup Colima
        run: brew install colima

      - name: Setup Docker
        run: brew install docker

      - name: Delete Colima
        run: colima delete -f

      - name: Start Colima
        run: colima start --vm-type vz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Change NODE_ENV to prod

      - name: Build Docker Image with Buildpacks
        run: npm run pack -- --publish

      - name: Stop Colima
        run: colima stop
