name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  build-and-publish-client:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: GHCR login (bypass keychain)
        run: |
          mkdir -p /tmp/docker-config
          echo '{}' > /tmp/docker-config/config.json
          echo "${{ secrets.GITHUB_TOKEN }}" | DOCKER_CONFIG=/tmp/docker-config docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # TODO: Change NODE_ENV to prod

      - name: Build Docker Image with Buildpacks
        run: npm run pack -- --publish
