name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  build-and-publish-client:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 25.2.1
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Setup Buildpacks Tools
        uses: buildpacks/github-actions/setup-tools@v5.10.0

      - name: Setup Buildpacks Pack
        uses: buildpacks/github-actions/setup-pack@v5.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image with Buildpacks
        run: npm run pack -- --publish