name: Keycloak CI

on:
  push:
    paths:
      - 'keycloak/**'

jobs:
  build-and-publish-keycloak:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build and Push Multi-Arch Keycloak Image
        working-directory: ./keycloak
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/is-stag-keycloak:latest \
            --push \
            .
