name: Keycloak CI

on:
  push:
    paths:
      - 'keycloak/**'

jobs:
  build-and-publish-keycloak:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Keycloak Image
        working-directory: ./keycloak
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/is-stag-keycloak:latest \
            --push \
            .
